//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testingRedService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MangaImage
    {
        public int Id { get; set; }
        public int MangaId { get; set; }
        public int Chapter { get; set; }
        public int Page { get; set; }
        public string ImagePath { get; set; }
    }
}
