//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class testingEntities : DbContext
    {
        public testingEntities()
            : base("name=testingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Manga> Mangas { get; set; }
        public DbSet<MangaChapter> MangaChapters { get; set; }
        public DbSet<MangaImage> MangaImages { get; set; }
        public DbSet<NewReleaseManga> NewReleaseMangas { get; set; }
    }
}
