//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewReleaseManga
    {
        public int MangaId { get; set; }
        public string MangaName { get; set; }
        public string Chapter { get; set; }
        public string ChapterName { get; set; }
        public string ChapterImagePath { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public bool IsEnable { get; set; }
    }
}
